import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,existsSync,rmSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {tmpdir} from 'node:os';
import {migratePeers,localIdentity,authenticate} from '../core/federation/peers.mjs';
import {issueCredential,listenPeerServer} from './helpers/peer-network.mjs';
import {migrateSync,digest,canonical} from '../core/federation/sync-store.mjs';
import {migrateBroker} from '../core/mcp/policy.mjs';
import {enrollTask} from '../core/mcp/tools.mjs';
import {migrateRelations,createRelationGraph,publishTopology,relationStatus,approveRelation,listRelationGraphs} from '../core/federation/relations.mjs';
import {migrateTopology,bindTopology,topologyState,prepareTopology,startTopologyAttempt,acceptTopologyReceipt} from '../core/federation/topology.mjs';
import {sendTopology} from '../core/federation/topology-client.mjs';
import {createBackup,restoreBackup} from '../core/backup.mjs';
import {prepareRecovery,activateRecovery,retireNode} from '../core/recovery.mjs';
const store=createRequire(import.meta.url)('../core/store.js'),TMP=mkdtempSync(join(tmpdir(),'fleet-graph-recovery-')),dbs=[],servers=[];let seq=0;
const moduleURL=new URL('../core/federation/graph-recovery.mjs',import.meta.url),api=existsSync(moduleURL)?await import(moduleURL):{};
after(async()=>{for(const s of servers){s.closeAllConnections();await new Promise(r=>s.close(r));}for(const db of dbs)try{db.close();}catch{}const r=relative(resolve(tmpdir()),resolve(TMP));assert.ok(r&&!r.startsWith('..'));rmSync(TMP,{recursive:true,force:true});});
const path=n=>join(TMP,n+'-'+seq++);
function node(){const dir=path('node');mkdirSync(dir);const dbPath=join(dir,'board.db'),db=new DatabaseSync(dbPath);dbs.push(db);db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000');store.migrate(db);migratePeers(db);migrateSync(db);migrateBroker(db);migrateRelations(db);migrateTopology(db);return {dir,dbPath,db,n:localIdentity(db)};}
function task(n){const id=store.add(n.db,{subject:'fixture '+seq++,released:true}),t=store.get(n.db,id);enrollTask(n.db,{id,projectId:'demo',workKind:'implement',capabilities:['board-tools'],expectedVersion:t.aggregate_version});return store.get(n.db,id);}
function grant(a,r){const file=path('credential')+'.json',prior=r.db.prepare('SELECT credential_version FROM federation_peers WHERE peer_node_id=?').get(a.n.node_id);issueCredential(r.db,{peerNodeId:a.n.node_id,peerEpoch:a.n.sync_epoch,scopes:['peer:handshake','relations:read','relations:publish','relations:approve'],projects:['demo'],credentialFile:file,expectedVersion:prior?.credential_version});return {file,peer:authenticate(r.db,'Bearer '+JSON.parse(readFileSync(file,'utf8')).token)};}
function prepare(a){return prepareTopology(a.db,{projectId:'demo',operationId:randomUUID(),expectedRevision:topologyState(a.db,'demo').revision,edits:[]});}
function publish(a,r,g){const op=prepare(a),v=listRelationGraphs(r.db).find(x=>x.project_id==='demo').version,args=startTopologyAttempt(a.db,{operationId:op.operation_id,expectedVersion:v});return acceptTopologyReceipt(a.db,{operationId:op.operation_id,requestId:args.request_id,receipt:publishTopology(r.db,g.peer,args)});}
function setup(){const a=node(),b=node(),r=node(),ta=task(a),tb=task(b),members=[a,b].map(n=>({node_id:n.n.node_id,node_epoch:n.n.sync_epoch})),g=createRelationGraph(r.db,{projectId:'demo',members}),ga=grant(a,r),gb=grant(b,r);for(const [n,c] of [[a,ga],[b,gb]]){bindTopology(n.db,{projectId:'demo',graphId:g.graph_id,graphEpoch:g.graph_epoch,registrarNodeId:r.n.node_id,registrarEpoch:r.n.sync_epoch});publish(n,r,c);}return {a,b,r,g,ga,gb,ta,tb,members};}
function restored(n){const evidence=path('evidence');mkdirSync(evidence);writeFileSync(join(evidence,'fixture.txt'),'only synthetic data');const backup=createBackup({dbPath:n.dbPath,evidenceDir:evidence,destination:path('backup')}),dir=path('restored');restoreBackup({backupDirectory:backup.destination,destination:dir});retireNode({dbPath:n.dbPath,expectedEpoch:n.n.sync_epoch});const dbPath=join(dir,'board.db'),p=prepareRecovery({dbPath});activateRecovery({dbPath,plan:p,expectedPlanDigest:p.plan_digest,attestation:{format:'ai-fleet-retirement-attestation/v1',node_id:p.node_id,retired_epoch:p.retired_epoch,plan_digest:p.plan_digest,original_board_stopped:true,original_agents_stopped:true,original_identity_disabled:true,other_restored_writers_stopped:true,evidence_ref:'isolated graph recovery fixture',attested_at:new Date().toISOString()}});const db=new DatabaseSync(dbPath);dbs.push(db);return {dir,dbPath,db,n:localIdentity(db)};}
function apiReady(){for(const f of ['prepareGraphRecovery','recordGraphRecovery','prepareTopologyRecovery','recordTopologyRecovery'])assert.equal(typeof api[f],'function','graph recovery must provide '+f);}
const graphPlan=f=>api.prepareGraphRecovery(f.r.db,{projectId:'demo',members:f.members});
function attest(p){return {format:'ai-fleet-graph-recovery-attestation/v1',node_id:p.node_id,node_epoch:p.node_epoch,plan_digest:p.plan_digest,member_confirmations:p.members.map(m=>({...m,old_graph_id:p.old_graph_id,old_graph_epoch:p.old_graph_epoch,old_work_stopped:true,pending_requests_reconciled:true,evidence_ref:'fixture member confirmation',attested_at:new Date().toISOString()})),unrecorded_confirmations_reconciled:true,evidence_ref:'fixture registry reconciliation',attested_at:new Date().toISOString()};}
const recover=(f,p=graphPlan(f))=>api.recordGraphRecovery(f.r.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:attest(p)});
function adopt(a,receipt){const p=api.prepareTopologyRecovery(a.db,{projectId:'demo',graphReceipt:receipt});return api.recordTopologyRecovery(a.db,{plan:p,expectedPlanDigest:p.plan_digest});}
const history=(r,id)=>canonical(Object.fromEntries(['relation_graphs','relation_members','relation_topologies','relation_requests','relation_events'].map(t=>[t,r.db.prepare('SELECT * FROM '+t+' WHERE graph_id=? ORDER BY rowid').all(id)])));

test('restored registrar creates a reviewed successor and an endpoint republishes over HTTP without rewriting old graph history',async()=>{
 const f=setup();f.r=restored(f.r);f.ga=grant(f.a,f.r);assert.throws(()=>relationStatus(f.r.db,f.ga.peer,{project_id:'demo',graph_id:f.g.graph_id,graph_epoch:f.g.graph_epoch,relation_id:null}),{code:'GRAPH_RECOVERY_REQUIRED'});apiReady();const before=history(f.r,f.g.graph_id),ro=new DatabaseSync(f.r.dbPath,{readOnly:true});let p;try{p=api.prepareGraphRecovery(ro,{projectId:'demo',members:f.members});}finally{ro.close();}assert.deepEqual(p.blockers,[]);const receipt=recover(f,p);assert.equal(history(f.r,f.g.graph_id),before);assert.notEqual(receipt.graph.graph_id,f.g.graph_id);assert.equal(receipt.graph.registrar_epoch,f.r.n.sync_epoch);assert.equal(listRelationGraphs(f.r.db).length,1);assert.throws(()=>relationStatus(f.r.db,f.ga.peer,{project_id:'demo',graph_id:f.g.graph_id,graph_epoch:f.g.graph_epoch,relation_id:null}),{code:'GRAPH_RETIRED'});
 const old=canonical(f.a.db.prepare('SELECT * FROM topology_bindings').get());adopt(f.a,receipt);assert.equal(canonical(f.a.db.prepare('SELECT * FROM topology_bindings').get()),old);assert.equal(topologyState(f.a.db,'demo').phase,'unregistered');assert.equal(store.get(f.a.db,f.ta.id).released,false);assert.equal(store.claimById(f.a.db,{id:f.ta.id,worker:'fixture'}).ok,false);
 const server=await listenPeerServer(f.r.db,{port:0});servers.push(server);const op=prepare(f.a),sent=await sendTopology(f.a.db,{operationId:op.operation_id,url:'http://127.0.0.1:'+server.address().port,credentialFile:f.ga.file});assert.equal(sent.state,'applied');assert.equal(topologyState(f.a.db,'demo').phase,'ready');assert.equal(store.claimById(f.a.db,{id:f.ta.id,worker:'fixture'}).ok,false);assert.equal(history(f.r,f.g.graph_id),before);assert.equal(f.a.db.prepare('SELECT count(*) n FROM task_runs').get().n,0);
});

test('pending relations, incomplete member confirmations and changed registry state refuse graph recovery',()=>{
 apiReady();const f=setup(),d={schema_version:1,type:'delegation',relation_id:randomUUID(),delegation_id:randomUUID(),project_id:'demo',graph_id:f.g.graph_id,graph_epoch:f.g.graph_epoch,source_node_id:f.a.n.node_id,source_epoch:f.a.n.sync_epoch,source_task_uid:f.ta.task_uid,target_node_id:f.b.n.node_id,target_epoch:f.b.n.sync_epoch,target_task_uid:f.tb.task_uid,offer_digest:'0'.repeat(64),source_topology_revision:1,target_topology_revision:1};approveRelation(f.r.db,f.ga.peer,{request_id:randomUUID(),expected_version:listRelationGraphs(f.r.db)[0].version,relation:d});f.r=restored(f.r);const p=graphPlan(f);assert.ok(p.blockers.some(b=>b.kind==='pending_relations'));assert.throws(()=>recover(f,p),{code:'GRAPH_RECOVERY_BLOCKED'});
 const clean=setup();clean.r=restored(clean.r);const plan=graphPlan(clean),a=attest(plan);a.member_confirmations.pop();assert.throws(()=>api.recordGraphRecovery(clean.r.db,{plan,expectedPlanDigest:plan.plan_digest,attestation:a}),{code:'MEMBER_CONFIRMATION_REQUIRED'});clean.r.db.prepare('UPDATE relation_graphs SET version=version+1').run();assert.throws(()=>recover(clean,plan),{code:'PLAN_STALE'});assert.equal(listRelationGraphs(clean.r.db)[0].graph_id,clean.g.graph_id);
});

test('restored owner adopts a new member epoch only after local pending operations are resolved and tasks stay held',()=>{
 apiReady();const f=setup();f.a=restored(f.a);f.members=f.members.map(m=>m.node_id===f.a.n.node_id?{...m,node_epoch:f.a.n.sync_epoch}:m);f.ga=grant(f.a,f.r);assert.throws(()=>topologyState(f.a.db,'demo'),{code:'TOPOLOGY_RECOVERY_REQUIRED'});const receipt=recover(f);const old=canonical(f.a.db.prepare('SELECT * FROM topology_bindings').get());adopt(f.a,receipt);assert.equal(canonical(f.a.db.prepare('SELECT * FROM topology_bindings').get()),old);assert.equal(topologyState(f.a.db,'demo').owner_epoch,f.a.n.sync_epoch);publish(f.a,f.r,f.ga);assert.equal(topologyState(f.a.db,'demo').phase,'ready');assert.equal(store.get(f.a.db,f.ta.id).human_gate,true);assert.throws(()=>f.a.db.prepare('UPDATE topology_binding_generations SET owner_epoch=?').run(randomUUID()),/immutable/);
 const busy=setup(),pending=prepare(busy.a);startTopologyAttempt(busy.a.db,{operationId:pending.operation_id,expectedVersion:listRelationGraphs(busy.r.db)[0].version});busy.r=restored(busy.r);const next=recover(busy),p=api.prepareTopologyRecovery(busy.a.db,{projectId:'demo',graphReceipt:next});assert.ok(p.blockers.some(b=>b.kind==='pending_topology'));assert.throws(()=>api.recordTopologyRecovery(busy.a.db,{plan:p,expectedPlanDigest:p.plan_digest}),{code:'TOPOLOGY_RECOVERY_BLOCKED'});assert.equal(topologyState(busy.a.db,'demo').phase,'pending');
});

test('ended unmanaged runs do not prove that endpoint executors stopped',()=>{
 apiReady();const f=setup();assert.equal(store.claimById(f.a.db,{id:f.ta.id,worker:'unmanaged-fixture'}).ok,true);f.a.db.prepare("UPDATE tasks SET status='waiting' WHERE id=?").run(f.ta.id);f.r=restored(f.r);const receipt=recover(f),p=api.prepareTopologyRecovery(f.a.db,{projectId:'demo',graphReceipt:receipt});assert.ok(p.blockers.some(b=>b.kind==='unmanaged_run'));assert.throws(()=>api.recordTopologyRecovery(f.a.db,{plan:p,expectedPlanDigest:p.plan_digest}),{code:'TOPOLOGY_RECOVERY_BLOCKED'});
});
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const cliPath=fileURLToPath(new URL('../cli/graph-recovery.mjs',import.meta.url));
function cli(command,dbPath,options){const r=spawnSync(process.execPath,[cliPath,command,'--db',dbPath,...Object.entries(options).flatMap(([k,v])=>['--'+k,v])],{encoding:'utf8',windowsHide:true,timeout:20000});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
function jsonFile(name,value){const file=path(name)+'.json';writeFileSync(file,JSON.stringify(value));return file;}
test('independent CLI commits idempotent generations, refuses forged receipts and rolls back failed endpoint persistence',()=>{
 apiReady();const f=setup();f.r=restored(f.r);const plan=cli('prepare-registrar',f.r.dbPath,{project:'demo','members-file':jsonFile('members',f.members)}),args={'plan-file':jsonFile('plan',plan),digest:plan.plan_digest,'attestation-file':jsonFile('attestation',attest(plan))},receipt=cli('apply-registrar',f.r.dbPath,args);assert.deepEqual(cli('apply-registrar',f.r.dbPath,args),receipt);assert.equal(f.r.db.prepare('SELECT count(*) n FROM relation_graph_transitions').get().n,1);
 const altered=structuredClone(receipt);altered.graph.registrar_epoch=randomUUID();assert.throws(()=>api.prepareTopologyRecovery(f.a.db,{projectId:'demo',graphReceipt:altered}),{code:'RECEIPT_MISMATCH'});
 const p=cli('prepare-topology',f.a.dbPath,{project:'demo','receipt-file':jsonFile('receipt',receipt)}),before=canonical(store.get(f.a.db,f.ta.id));f.a.db.exec("CREATE TRIGGER fixture_fail_recovery BEFORE INSERT ON topology_recoveries BEGIN SELECT RAISE(ABORT,'fixture ledger failure'); END");assert.throws(()=>api.recordTopologyRecovery(f.a.db,{plan:p,expectedPlanDigest:p.plan_digest}),/fixture ledger failure/);assert.equal(canonical(store.get(f.a.db,f.ta.id)),before);assert.equal(f.a.db.prepare('SELECT count(*) n FROM topology_binding_generations').get().n,0);f.a.db.exec('DROP TRIGGER fixture_fail_recovery');const options={'plan-file':jsonFile('topology-plan',p),digest:p.plan_digest},result=cli('apply-topology',f.a.dbPath,options);assert.deepEqual(cli('apply-topology',f.a.dbPath,options),result);
 f.ga=grant(f.a,f.r);publish(f.a,f.r,f.ga);const t=store.get(f.a.db,f.ta.id);store.update(f.a.db,{id:t.id,expectedVersion:t.aggregate_version,humanGate:false,actor:'human'});store.setReleased(f.a.db,{id:t.id,expectedVersion:store.get(f.a.db,t.id).aggregate_version,released:true,actor:'human'});assert.equal(store.claimById(f.a.db,{id:t.id,worker:'explicitly-released-fixture'}).ok,true);
});
