import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {prepareBindingRecovery,recordBindingRecovery} from '../core/federation/binding-recovery.mjs';
import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {tmpdir} from 'node:os';
import {migratePeers,localIdentity,authenticate} from '../core/federation/peers.mjs';
import {issueCredential} from './helpers/peer-network.mjs';
import {digest,canonical} from '../core/federation/sync-store.mjs';
import {enrollTask} from '../core/mcp/tools.mjs';
import {migrateBindings,prepareBinding,bindingMessage,receiveBindingMessage,recordBindingMessage,startBindingAttempt,acceptBindingReceipt,bindingState,declineBindingProposal} from '../core/federation/bindings.mjs';
import {createIntent,receiveOffer,decideIncoming,recordReceipt} from '../core/federation/delegation.mjs';
import {migrateRelations,createRelationGraph,publishTopology,approveRelation,relationStatus,localRegistrarPeer,listRelationGraphs} from '../core/federation/relations.mjs';
import {bindTopology,prepareTopology,startTopologyAttempt,acceptTopologyReceipt} from '../core/federation/topology.mjs';
import {migrateCancellations,prepareCancellation,receiveCancellation,confirmCancellationStopped,recordCancellationReceipt} from '../core/federation/cancellation.mjs';
import {prepareGraphRecovery,recordGraphRecovery,prepareTopologyRecovery,recordTopologyRecovery} from '../core/federation/graph-recovery.mjs';
import {createBackup,restoreBackup} from '../core/backup.mjs';
import {prepareRecovery,activateRecovery,retireNode} from '../core/recovery.mjs';
const store=createRequire(import.meta.url)('../core/store.js'),ROOT=mkdtempSync(join(tmpdir(),'fleet-pending-relation-')),dbs=[];let serial=0;
const moduleURL=new URL('../core/federation/pending-relation-recovery.mjs',import.meta.url),api=existsSync(moduleURL)?await import(moduleURL):{};
const path=label=>join(ROOT,label+'-'+serial++),at=()=>new Date().toISOString();
after(()=>{for(const db of dbs)try{db.close();}catch{}const p=relative(resolve(tmpdir()),resolve(ROOT));assert.ok(p&&!p.startsWith('..'));rmSync(ROOT,{recursive:true,force:true});});
function node(){const dir=path('node');mkdirSync(dir);const dbPath=join(dir,'board.db'),db=new DatabaseSync(dbPath);dbs.push(db);db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000');store.migrate(db);migratePeers(db);migrateBindings(db);migrateCancellations(db);migrateRelations(db);return {dir,dbPath,db,n:localIdentity(db)};}
function grant(a,b,scopes){const credentialFile=path('credential')+'.json';issueCredential(b.db,{peerNodeId:a.n.node_id,peerEpoch:a.n.sync_epoch,scopes,projects:['demo'],credentialFile,expectedVersion:b.db.prepare('SELECT credential_version FROM federation_peers WHERE peer_node_id=?').get(a.n.node_id)?.credential_version});return authenticate(b.db,'Bearer '+JSON.parse(readFileSync(credentialFile,'utf8')).token);}
function card(n){const id=store.add(n.db,{subject:'preserved work',description:'contract fixture',acceptance:'independent review',treeMode:'hierarchical',route:'mcp',released:true}),t=store.get(n.db,id);enrollTask(n.db,{id,projectId:'demo',workKind:'implement',capabilities:['board-tools'],expectedVersion:t.aggregate_version});return store.get(n.db,id);}
function fixture({targetPrepared=true,targetReceived=true,confirmed=false,localRegistrar=false}={}){
 const a=node(),b=node(),r=localRegistrar?a:node(),source=card(a),ab=grant(a,b,['peer:handshake','delegation:offer','delegation:status','delegation:binding','delegation:control']),ar=localRegistrar?localRegistrarPeer(a.db,'demo'):grant(a,r,['peer:handshake','relations:read','relations:approve','relations:publish']),br=grant(b,r,['peer:handshake','relations:read','relations:approve','relations:publish']);
 const out=createIntent(a.db,{delegationId:randomUUID(),taskUid:source.task_uid,expectedVersion:source.aggregate_version,targetNodeId:b.n.node_id,targetEpoch:b.n.sync_epoch});receiveOffer(b.db,ab,out.offer);const accepted=decideIncoming(b.db,{delegationId:out.delegation_id,decisionId:randomUUID(),expectedVersion:1,decision:'accept',note:'fixture'});recordReceipt(a.db,out.delegation_id,accepted);
 const target=store.get(b.db,b.db.prepare('SELECT id FROM tasks WHERE task_uid=?').get(accepted.target_task_uid).id),members=[a,b].map(n=>({node_id:n.n.node_id,node_epoch:n.n.sync_epoch})),g=createRelationGraph(r.db,{projectId:'demo',members});
 for(const [n,peer] of [[a,ar],[b,br]]){bindTopology(n.db,{projectId:'demo',graphId:g.graph_id,graphEpoch:g.graph_epoch,registrarNodeId:r.n.node_id,registrarEpoch:r.n.sync_epoch});const op=prepareTopology(n.db,{projectId:'demo',operationId:randomUUID(),expectedRevision:0}),args=startTopologyAttempt(n.db,{operationId:op.operation_id,expectedVersion:r.db.prepare('SELECT version FROM relation_graphs').get().version});acceptTopologyReceipt(n.db,{operationId:op.operation_id,requestId:args.request_id,receipt:publishTopology(r.db,peer,args)});}
 const d={schema_version:1,type:'delegation',relation_id:randomUUID(),delegation_id:out.delegation_id,project_id:'demo',graph_id:g.graph_id,graph_epoch:g.graph_epoch,source_node_id:a.n.node_id,source_epoch:a.n.sync_epoch,source_task_uid:source.task_uid,target_node_id:b.n.node_id,target_epoch:b.n.sync_epoch,target_task_uid:target.task_uid,offer_digest:out.offer_digest,source_topology_revision:1,target_topology_revision:1};
 const approve=(n,peer)=>{const args=startBindingAttempt(n.db,{relationId:d.relation_id,expectedVersion:r.db.prepare('SELECT version FROM relation_graphs').get().version});return acceptBindingReceipt(n.db,{relationId:d.relation_id,requestId:args.request_id,receipt:approveRelation(r.db,peer,args)});};
 const send=kind=>{const body=bindingMessage(a.db,{relationId:d.relation_id,kind});recordBindingMessage(a.db,{requestId:body.request_id,receipt:receiveBindingMessage(b.db,ab,body)});};
 prepareBinding(a.db,{relation:d,expectedTaskVersion:store.get(a.db,source.id).aggregate_version});approve(a,ar);if(targetReceived)send('proposal');
 if(targetPrepared){prepareBinding(b.db,{relation:d,expectedTaskVersion:store.get(b.db,target.id).aggregate_version});const args=startBindingAttempt(b.db,{relationId:d.relation_id,expectedVersion:listRelationGraphs(r.db)[0].version});if(confirmed)approveRelation(r.db,br,args);}
 else if(targetReceived)declineBindingProposal(b.db,{relationId:d.relation_id,expectedDescriptorDigest:digest(d),reasonCode:'operator_declined'});
 return {a,b,r,source,target,d,members,g,ar,br};
}

function restored(n){const evidenceDir=path('evidence');mkdirSync(evidenceDir);writeFileSync(join(evidenceDir,'item.txt'),'preserved synthetic evidence');const backup=createBackup({dbPath:n.dbPath,evidenceDir,destination:path('backup')}),dir=path('restored');restoreBackup({backupDirectory:backup.destination,destination:dir});retireNode({dbPath:n.dbPath,expectedEpoch:n.n.sync_epoch});const dbPath=join(dir,'board.db'),p=prepareRecovery({dbPath});activateRecovery({dbPath,plan:p,expectedPlanDigest:p.plan_digest,attestation:{format:'ai-fleet-retirement-attestation/v1',node_id:p.node_id,retired_epoch:p.retired_epoch,plan_digest:p.plan_digest,original_board_stopped:true,original_agents_stopped:true,original_identity_disabled:true,other_restored_writers_stopped:true,evidence_ref:'isolated restored registrar fixture',attested_at:at()}});const db=new DatabaseSync(dbPath);dbs.push(db);return {dir,dbPath,db,n:localIdentity(db)};}
function ready(){for(const name of ['pendingRelationEndpointEvidence','preparePendingRelationRecovery','recordPendingRelationRecovery'])assert.equal(typeof api[name],'function',name+' must connect endpoint exits to registrar recovery');}
const attestations=new Map();
function endpointExit(n,f){
 if(n.db.prepare('SELECT state FROM delegation_bindings WHERE relation_id=?').get(f.d.relation_id)?.state!=='prepared')return;
 const p=prepareBindingRecovery(n.db,{relationId:f.d.relation_id,registrarEpoch:f.r.n.sync_epoch}),a={format:'ai-fleet-binding-recovery-attestation/v1',...Object.fromEntries(['node_id','node_epoch','binding_epoch','relation_id','registrar_node_id','retired_registrar_epoch','observed_registrar_epoch','plan_digest'].map(k=>[k,p[k]])),old_registrar_disabled:true,both_endpoint_workers_stopped:true,remote_outcome_unknown:true,no_automatic_release:true,evidence_ref:'isolated endpoint exit',attested_at:at()};
 return recordBindingRecovery(n.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:a});
}
function attestation(p){if(attestations.has(p.plan_digest))return attestations.get(p.plan_digest);const a={format:'ai-fleet-pending-relation-recovery-attestation/v1',node_id:p.node_id,node_epoch:p.node_epoch,plan_digest:p.plan_digest,old_registrar_disabled:true,both_endpoint_records_reviewed:true,remote_outcome_unknown:true,no_automatic_release:true,evidence_ref:'isolated proposal recovery review',attested_at:at()};attestations.set(p.plan_digest,a);return a;}
function endpoints(f){return [f.a,f.b].map(n=>{endpointExit(n,f);return api.pendingRelationEndpointEvidence(n.db,{relation:f.d,registrarEpoch:f.r.n.sync_epoch});});}
function recover(f,e=endpoints(f)){const p=api.preparePendingRelationRecovery(f.r.db,{relationId:f.d.relation_id,endpointEvidence:e});return api.recordPendingRelationRecovery(f.r.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:attestation(p)});}
function graph(f){const p=prepareGraphRecovery(f.r.db,{projectId:'demo',members:f.members});assert.deepEqual(p.blockers,[]);return recordGraphRecovery(f.r.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:{format:'ai-fleet-graph-recovery-attestation/v1',node_id:p.node_id,node_epoch:p.node_epoch,plan_digest:p.plan_digest,unrecorded_confirmations_reconciled:true,evidence_ref:'isolated reconciled graph',attested_at:at(),member_confirmations:p.members.map(m=>({...m,old_graph_id:p.old_graph_id,old_graph_epoch:p.old_graph_epoch,old_work_stopped:true,pending_requests_reconciled:true,evidence_ref:'isolated stopped member',attested_at:at()}))}});}


test('pending relation exits unblock an actual restored registrar without fabricating a normal withdrawal or discarding endpoint history',()=>{
 const f=fixture(),old=canonical(f.r.db.prepare('SELECT * FROM relation_proposals').all());f.r=restored(f.r);for(const n of [f.a,f.b])endpointExit(n,f);
 assert.ok(prepareGraphRecovery(f.r.db,{projectId:'demo',members:f.members}).blockers.some(b=>b.kind==='pending_relations'));
 ready();const r=recover(f);assert.equal(r.remote_outcome_known,false);assert.equal(r.automatic_release,false);assert.equal(f.r.db.prepare('SELECT count(*) n FROM relation_withdrawals').get().n,0);assert.equal(canonical(f.r.db.prepare('SELECT * FROM relation_proposals').all()),old);
 const next=graph(f);for(const n of [f.a,f.b]){const p=prepareTopologyRecovery(n.db,{projectId:'demo',graphReceipt:next});assert.deepEqual(p.blockers,[]);recordTopologyRecovery(n.db,{plan:p,expectedPlanDigest:p.plan_digest});assert.equal(n.db.prepare('SELECT count(*) n FROM task_runs').get().n,0);assert.equal(store.claimById(n.db,{id:n===f.a?f.source.id:f.target.id,worker:'unreleased-fixture'}).ok,false);}
});

const rehashEvidence=e=>{const {evidence_digest,...body}=e;return {...body,evidence_digest:digest(body)};};
const tableCount=(db,t)=>db.prepare('SELECT count(*) n FROM '+t).get().n;
function republish(f,n){const op=prepareTopology(n.db,{projectId:'demo',operationId:randomUUID(),expectedRevision:0}),peer=n===f.r?localRegistrarPeer(n.db,'demo'):grant(n,f.r,['peer:handshake','relations:read','relations:approve','relations:publish']),args=startTopologyAttempt(n.db,{operationId:op.operation_id,expectedVersion:listRelationGraphs(f.r.db)[0].version});acceptTopologyReceipt(n.db,{operationId:op.operation_id,requestId:args.request_id,receipt:publishTopology(f.r.db,peer,args)});}
test('two-node source-as-registrar layout handles declined or never-delivered target proposals and keeps source and registrar identity together',()=>{
 ready();for(const targetReceived of [true,false]){const f=fixture({localRegistrar:true,targetPrepared:false,targetReceived});f.a=restored(f.a);f.r=f.a;f.members=[f.a,f.b].map(n=>({node_id:n.n.node_id,node_epoch:n.n.sync_epoch}));const e=endpoints(f);assert.equal(e.find(x=>x.side==='target').local_disposition,targetReceived?'declined_unprepared':'never_prepared');recover(f,e);const next=graph(f);
 for(const n of [f.a,f.b]){const p=prepareTopologyRecovery(n.db,{projectId:'demo',graphReceipt:next});recordTopologyRecovery(n.db,{plan:p,expectedPlanDigest:p.plan_digest});republish(f,n);assert.equal(store.claimById(n.db,{id:n===f.a?f.source.id:f.target.id,worker:'held'}).ok,false);}
 assert.equal(tableCount(f.b.db,'delegation_bindings'),0);store.update(f.a.db,{id:f.source.id,humanGate:false,expectedVersion:store.get(f.a.db,f.source.id).aggregate_version,actor:'human'});store.setReleased(f.a.db,{id:f.source.id,released:true,expectedVersion:store.get(f.a.db,f.source.id).aggregate_version,actor:'human'});assert.equal(store.claimById(f.a.db,{id:f.source.id,worker:'explicit-owner-release'}).ok,true);assert.equal(tableCount(f.b.db,'task_runs'),0);
 }});
test('known registrar confirmation or endpoint commitment refuses pending retirement even if a confirmation reply was lost',()=>{
 ready();const f=fixture({confirmed:true}),edge=canonical(f.r.db.prepare('SELECT * FROM relation_edges').all());f.r=restored(f.r);const evidence=endpoints(f);assert.throws(()=>api.preparePendingRelationRecovery(f.r.db,{relationId:f.d.relation_id,endpointEvidence:evidence}),{code:'RELATION_CONFIRMED'});assert.equal(canonical(f.r.db.prepare('SELECT * FROM relation_edges').all()),edge);assert.ok(prepareGraphRecovery(f.r.db,{projectId:'demo',members:f.members}).blockers.some(x=>x.kind==='active_relations'));
 const known=fixture({confirmed:true});acceptBindingReceipt(known.b.db,{relationId:known.d.relation_id,receipt:relationStatus(known.r.db,known.br,{project_id:'demo',graph_id:known.g.graph_id,graph_epoch:known.g.graph_epoch,relation_id:known.d.relation_id})});known.r=restored(known.r);assert.throws(()=>api.pendingRelationEndpointEvidence(known.b.db,{relation:known.d,registrarEpoch:known.r.n.sync_epoch}),{code:'RELATION_CONFIRMED'});
});
test('endpoint evidence is read-only and requires durable exits, matching pairs, and actual stopped-run evidence',()=>{
 ready();const f=fixture();f.r=restored(f.r);assert.throws(()=>api.pendingRelationEndpointEvidence(f.b.db,{relation:f.d,registrarEpoch:f.r.n.sync_epoch}),{code:'BINDING_RECOVERY_REQUIRED'});const e=endpoints(f),before=canonical(f.a.db.prepare('SELECT * FROM task_events').all()),ro=new DatabaseSync(f.a.dbPath,{readOnly:true});try{assert.equal(api.pendingRelationEndpointEvidence(ro,{relation:f.d,registrarEpoch:f.r.n.sync_epoch}).state_digest,e[0].state_digest);}finally{ro.close();}assert.equal(canonical(f.a.db.prepare('SELECT * FROM task_events').all()),before);
 for(const bad of [[e[0]],[e[0],e[0]],[e[0],rehashEvidence({...e[1],descriptor_digest:'a'.repeat(64)})],[e[0],rehashEvidence({...e[1],observed_registrar_epoch:randomUUID()})]])assert.throws(()=>api.preparePendingRelationRecovery(f.r.db,{relationId:f.d.relation_id,endpointEvidence:bad}),{code:'ENDPOINT_EVIDENCE_REQUIRED'});
 store.update(f.a.db,{id:f.source.id,humanGate:false,actor:'human'});store.setReleased(f.a.db,{id:f.source.id,released:true,actor:'human'});assert.equal(store.claimById(f.a.db,{id:f.source.id,worker:'unmanaged-fixture'}).ok,true);f.a.db.prepare("UPDATE tasks SET status='waiting' WHERE id=?").run(f.source.id);store.setReleased(f.a.db,{id:f.source.id,released:false,actor:'human'});assert.throws(()=>api.pendingRelationEndpointEvidence(f.a.db,{relation:f.d,registrarEpoch:f.r.n.sync_epoch}),{code:'STOP_UNCONFIRMED'});
});
test('stale or incomplete review refuses recovery and failed audit leaves the pending graph blocker intact',()=>{
 ready();const f=fixture();f.r=restored(f.r);const e=endpoints(f),prepare=()=>api.preparePendingRelationRecovery(f.r.db,{relationId:f.d.relation_id,endpointEvidence:e});let p=prepare();const record=(p,a=attestation(p))=>api.recordPendingRelationRecovery(f.r.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:a});assert.throws(()=>record(p,{...attestation(p),old_registrar_disabled:false}),{code:'ATTESTATION_MISMATCH'});
 f.r.db.prepare('UPDATE relation_graphs SET version=version+1 WHERE graph_id=?').run(f.g.graph_id);assert.throws(()=>record(p),{code:'PLAN_STALE'});p=prepare();api.migratePendingRelationRecovery(f.r.db);f.r.db.exec("CREATE TRIGGER fixture_pending_retirement BEFORE INSERT ON relation_recovery_withdrawals BEGIN SELECT RAISE(ABORT,'fixture retirement audit failed'); END");const old=canonical(f.r.db.prepare('SELECT * FROM relation_proposals').all());assert.throws(()=>record(p),/fixture retirement audit failed/);assert.equal(tableCount(f.r.db,'relation_recovery_withdrawals'),0);assert.equal(canonical(f.r.db.prepare('SELECT * FROM relation_proposals').all()),old);assert.ok(prepareGraphRecovery(f.r.db,{projectId:'demo',members:f.members}).blockers.some(x=>x.kind==='pending_relations'));
 f.r.db.exec('DROP TRIGGER fixture_pending_retirement');const r=record(p);assert.deepEqual(record(p),r);assert.throws(()=>record(p,{...attestation(p),evidence_ref:'changed reviewer evidence'}),{code:'REQUEST_CONFLICT'});assert.equal(tableCount(f.r.db,'relation_recovery_withdrawals'),1);assert.throws(()=>f.r.db.prepare("UPDATE relation_recovery_withdrawals SET receipt_json='{}'").run(),/immutable/);assert.throws(()=>f.r.db.prepare('DELETE FROM relation_recovery_withdrawals').run(),/retained/);
});
test('colocated endpoint evidence is rechecked against current local data before registrar persistence',()=>{
 const f=fixture({localRegistrar:true});f.a=restored(f.a);f.r=f.a;const e=endpoints(f),p=api.preparePendingRelationRecovery(f.r.db,{relationId:f.d.relation_id,endpointEvidence:e});store.update(f.a.db,{id:f.source.id,description:'reviewed contract context changed',actor:'human'});assert.throws(()=>api.recordPendingRelationRecovery(f.r.db,{plan:p,expectedPlanDigest:p.plan_digest,attestation:attestation(p)}),{code:'PLAN_STALE'});
});
const cliPath=fileURLToPath(new URL('../cli/pending-relation-recovery.mjs',import.meta.url));
function cli(command,n,options){return spawnSync(process.execPath,[cliPath,command,'--db',n.dbPath,...Object.entries(options).flatMap(([k,v])=>['--'+k,v])],{encoding:'utf8',windowsHide:true,timeout:20000});}
function jsonFile(name,v){const f=path(name)+'.json';writeFileSync(f,JSON.stringify(v));return f;}
test('pending proposal CLI exports local evidence, records one reviewed decision and sanitizes argument failures',()=>{
 const f=fixture({targetPrepared:false});f.r=restored(f.r);endpointExit(f.a,f);const evidence=[];for(const n of [f.a,f.b]){const result=cli('endpoint-evidence',n,{'relation-file':jsonFile('descriptor',f.d),'registrar-epoch':f.r.n.sync_epoch});assert.equal(result.status,0,result.stderr);evidence.push(JSON.parse(result.stdout));}
 const prepared=cli('prepare-registrar',f.r,{relation:f.d.relation_id,'evidence-file':jsonFile('evidence',evidence)});assert.equal(prepared.status,0,prepared.stderr);const p=JSON.parse(prepared.stdout),args={'plan-file':jsonFile('plan',p),digest:p.plan_digest,'attestation-file':jsonFile('attestation',attestation(p))},recorded=cli('record-registrar',f.r,args);assert.equal(recorded.status,0,recorded.stderr);assert.deepEqual(JSON.parse(cli('record-registrar',f.r,args).stdout),JSON.parse(recorded.stdout));assert.deepEqual(JSON.parse(cli('status',f.r,{relation:f.d.relation_id}).stdout),JSON.parse(recorded.stdout));
 const bad=cli('endpoint-evidence',f.a,{'relation-file':jsonFile('bad-descriptor',{}),'registrar-epoch':f.r.n.sync_epoch,'unexpected-option':'PRIVATE_SENTINEL'});assert.equal(bad.status,1);assert.ok(!bad.stderr.includes('PRIVATE_SENTINEL'));assert.ok(!bad.stderr.includes(f.a.dbPath));
});
