import {join} from "node:path";
import {PeerError,uuid} from "../federation/protocol.mjs";
import {localIdentity,transaction} from "../federation/peers.mjs";
import {canonical,digest} from "../federation/sync-store.mjs";
import {captureVerificationReceipt,assertVerificationReceiptCurrent,migrateVerification} from "../verification/service.mjs";
import {artifactState,captureVerifiedArtifact} from "../artifacts/transfers.mjs";
import {repositoryState,workspaceRepositorySource} from "../artifacts/repositories.mjs";
import {directoryIdentity,verifyDirectory,overlaps} from "../artifacts/git-workspace.mjs";
import {integrationRef,integrationGit,sourceIdentities,importIntegrationObjects,verifyIntegrationObjects} from "./git.mjs";
const fail=(code,message)=>{throw new PeerError(code,message,409);},at=()=>new Date().toISOString();
function outside(db){if(db.isTransaction)fail("TRANSACTION_CONTEXT","来源合并准备须在写事务外调用");}
function separate(a,b){if(overlaps(a,b)||overlaps(b,a))fail("INTEGRATION_PATH_OVERLAP","合并临时目录与来源、治理目录或数据库重叠");}
function identity(db,r){const n=localIdentity(db);if(r.node_id!==n.node_id||r.node_epoch!==n.sync_epoch)fail("INTEGRATION_RECOVERY_REQUIRED","旧代次合并记录不可继续执行");}
function codeSource(gate){const s=gate?.check?.();if(!s||typeof s.code_root!=="string"||!s.code_root||!/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/.test(s.tree))fail("SOURCE_UNVERIFIED","来源合并需要有效治理树验收");return {code_root:s.code_root,tree:s.tree};}
export function migrateIntegration(db){outside(db);migrateVerification(db);return transaction(db,()=>{
 db.exec("CREATE TABLE IF NOT EXISTS integration_schema(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version INTEGER NOT NULL); INSERT OR IGNORE INTO integration_schema VALUES(1,1)");
 if(db.prepare("SELECT version FROM integration_schema").get().version!==1)fail("SCHEMA_INCOMPATIBLE","来源合并存储版本不兼容");
 db.exec([
 "CREATE TABLE IF NOT EXISTS integration_policies(policy_id TEXT PRIMARY KEY,node_id TEXT NOT NULL,node_epoch TEXT NOT NULL,mapping_id TEXT NOT NULL,descriptor_json TEXT NOT NULL,descriptor_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_revocations(policy_id TEXT PRIMARY KEY,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_attempts(integration_id TEXT PRIMARY KEY,node_id TEXT NOT NULL,node_epoch TEXT NOT NULL,policy_id TEXT NOT NULL,verification_id TEXT NOT NULL,result_id TEXT NOT NULL,binding_json TEXT NOT NULL,binding_digest TEXT NOT NULL,intent_json TEXT NOT NULL,intent_digest TEXT NOT NULL,commit_timestamp INTEGER NOT NULL,container TEXT NOT NULL,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_objects(integration_id TEXT PRIMARY KEY,objects_json TEXT NOT NULL,objects_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_launches(integration_id TEXT PRIMARY KEY,binding_digest TEXT NOT NULL,objects_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_receipts(integration_id TEXT PRIMARY KEY,receipt_json TEXT NOT NULL,receipt_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
 "CREATE TABLE IF NOT EXISTS integration_abandons(integration_id TEXT PRIMARY KEY,reason TEXT NOT NULL,created_at TEXT NOT NULL);"
 ].join("\n"));
 for(const t of ["integration_policies","integration_revocations","integration_attempts","integration_objects","integration_launches","integration_receipts","integration_abandons"]){db.exec("CREATE TRIGGER IF NOT EXISTS "+t+"_immutable BEFORE UPDATE ON "+t+" BEGIN SELECT RAISE(ABORT,'integration history is immutable'); END");db.exec("CREATE TRIGGER IF NOT EXISTS "+t+"_retained BEFORE DELETE ON "+t+" BEGIN SELECT RAISE(ABORT,'integration history must be retained'); END");}
});}
function policy(db,id,{active=true}={}){uuid(id,"policy_id");const r=db.prepare("SELECT * FROM integration_policies WHERE policy_id=?").get(id);if(!r)fail("NOT_FOUND","来源合并配置不存在");identity(db,r);if(active&&db.prepare("SELECT 1 FROM integration_revocations WHERE policy_id=?").get(id))fail("INTEGRATION_REVOKED","来源合并配置已撤销");const descriptor=JSON.parse(r.descriptor_json);if(digest(descriptor)!==r.descriptor_digest)fail("INTEGRATION_CORRUPT","来源合并配置摘要不同");return {...r,descriptor};}
function repositoryDescriptor(s){return {root:s.root,common_dir:s.common_dir,object_format:s.object_format,git:s.git,allowed_paths:s.allowed_paths};}
function sourceFor(db,p,base){const source=workspaceRepositorySource(db,{mappingId:p.mapping_id,baseCommit:base});if(canonical(repositoryDescriptor(source))!==canonical(p.descriptor.repository))fail("INTEGRATION_REPOSITORY_CHANGED","来源仓库映射已变化");verifyDirectory(p.descriptor.identities.repo);verifyDirectory(p.descriptor.identities.common);verifyDirectory(p.descriptor.pool);return source;}
/** Trusted local operator configuration. The selected ref has one local integration writer. */
export function registerIntegrationPolicy(db,{policyId,mappingId,ref,poolRoot,allowVerifiedContentMerge,exclusiveRefManagement,sourceGate}){
 outside(db);uuid(policyId,"policy_id");uuid(mappingId,"mapping_id");integrationRef(ref);if(process.platform!=="win32")fail("WINDOWS_REQUIRED","来源合并仅支持 Windows");
 if(allowVerifiedContentMerge!==true||exclusiveRefManagement!==true)fail("INTEGRATION_PERMISSION_REQUIRED","需明确批准实际内容合并及该引用由本机服务独占管理");
 const source=codeSource(sourceGate),pool=directoryIdentity(poolRoot),mapping=repositoryState(db,{mappingId}),repo=workspaceRepositorySource(db,{mappingId,baseCommit:mapping.approved_bases[0]?.commit_oid}),identities=sourceIdentities(repo);
 for(const path of [source.code_root,repo.root,repo.common_dir,db.prepare("PRAGMA database_list").all().find(x=>x.name==="main")?.file])if(path)separate(pool.root,path);
 const git=integrationGit({source:repo,identities});git.checkoutGuard(ref);const oid=git.refValue(ref);if(!mapping.approved_bases.some(b=>b.commit_oid===oid))fail("BASE_NOT_APPROVED","来源目标引用必须已存在且指向本机批准基线");
 const descriptor={mapping_id:mappingId,ref,pool,repository:repositoryDescriptor(repo),identities,source,allow_verified_content_merge:true,exclusive_ref_management:true};migrateIntegration(db);
 return transaction(db,()=>{const old=db.prepare("SELECT * FROM integration_policies WHERE policy_id=?").get(policyId),n=localIdentity(db);if(old){policy(db,policyId);if(old.descriptor_json!==canonical(descriptor))fail("REQUEST_CONFLICT","合并配置编号已固定");}else{if(db.prepare("SELECT count(*) n FROM integration_policies").get().n>=1000)fail("INTEGRATION_LIMIT","保留合并配置达到上限");db.prepare("INSERT INTO integration_policies VALUES(?,?,?,?,?,?,?)").run(policyId,n.node_id,n.sync_epoch,mappingId,canonical(descriptor),digest(descriptor),at());}return {policy_id:policyId,mapping_id:mappingId,ref,policy_digest:digest(descriptor),accepted:false};});
}
export function revokeIntegrationPolicy(db,{policyId}){return transaction(db,()=>{policy(db,policyId,{active:false});db.prepare("INSERT OR IGNORE INTO integration_revocations VALUES(?,?)").run(policyId,at());return {policy_id:policyId,revoked:true};});}
function row(db,id){uuid(id,"integration_id");const r=db.prepare("SELECT * FROM integration_attempts WHERE integration_id=?").get(id);if(!r)fail("NOT_FOUND","来源合并运行不存在");identity(db,r);if(digest(JSON.parse(r.binding_json))!==r.binding_digest||digest(JSON.parse(r.intent_json))!==r.intent_digest)fail("INTEGRATION_CORRUPT","来源合并绑定摘要变化");return r;}
function objects(db,id){const r=db.prepare("SELECT * FROM integration_objects WHERE integration_id=?").get(id);if(!r)fail("INTEGRATION_NOT_READY","来源对象尚未准备完成；保留部分目录，不自动覆盖");const o=JSON.parse(r.objects_json);if(digest(o)!==r.objects_digest)fail("INTEGRATION_CORRUPT","来源对象摘要变化");return o;}
function current(db,r,sourceGate){const p=policy(db,r.policy_id),b=JSON.parse(r.binding_json);if(p.descriptor_digest!==b.policy_digest||canonical(codeSource(sourceGate))!==canonical(p.descriptor.source))fail("SOURCE_CHANGED","来源合并的批准配置或治理树改变");const v=assertVerificationReceiptCurrent(db,{verificationId:r.verification_id,receiptDigest:b.verification_receipt_digest,sourceGate});if(digest(v.binding)!==b.verification_binding_digest)fail("INTEGRATION_STALE","来源验证上下文变化");return p;}
export function integrationState(db,id){const r=row(db,id),o=db.prepare("SELECT objects_digest FROM integration_objects WHERE integration_id=?").get(id),l=db.prepare("SELECT * FROM integration_launches WHERE integration_id=?").get(id),s=db.prepare("SELECT * FROM integration_receipts WHERE integration_id=?").get(id),a=db.prepare("SELECT reason FROM integration_abandons WHERE integration_id=?").get(id);if(s&&digest(JSON.parse(s.receipt_json))!==s.receipt_digest)fail("INTEGRATION_CORRUPT","合并回执摘要变化");return {integration_id:id,phase:s?"settled":a?"abandoned":l?"launch_committed":o?"ready":"preparing",binding:JSON.parse(r.binding_json),binding_digest:r.binding_digest,objects_digest:o?.objects_digest??null,receipt:s?JSON.parse(s.receipt_json):null,receipt_digest:s?.receipt_digest??null,abandon_reason:a?.reason??null,accepted:false};}
export function prepareIntegration(db,{integrationId,policyId,verificationId,sourceGate}){
 outside(db);uuid(integrationId,"integration_id");uuid(verificationId,"verification_id");migrateIntegration(db);const p=policy(db,policyId),v=captureVerificationReceipt(db,{verificationId,sourceGate}),captured=captureVerifiedArtifact(db,{transferId:v.binding.transfer_id}),h=captured.header,source=sourceFor(db,p,h.manifest.base_commit);
 if(captured.mapping_id!==p.mapping_id||canonical(v.binding.source)!==canonical(p.descriptor.source)||canonical(codeSource(sourceGate))!==canonical(p.descriptor.source))fail("INTEGRATION_MAPPING_MISMATCH","产物、来源配置或治理代码不同");
 const binding={policy_id:policyId,policy_digest:p.descriptor_digest,mapping_id:p.mapping_id,ref:p.descriptor.ref,verification_id:verificationId,verification_receipt_digest:v.receipt_digest,verification_binding_digest:digest(v.binding),transfer_id:h.transfer_id,header_digest:captured.header_digest,result_id:h.result_id,base_commit:h.manifest.base_commit,artifact_commit:h.manifest.commit,tree:h.manifest.tree};
 const old=db.prepare("SELECT integration_id FROM integration_attempts WHERE integration_id=?").get(integrationId);if(old){const r=row(db,integrationId);if(r.binding_json!==canonical(binding))fail("REQUEST_CONFLICT","合并编号已绑定其他候选");return integrationState(db,integrationId);}
 const git=integrationGit({source,identities:p.descriptor.identities});git.checkoutGuard(binding.ref);if(git.refValue(binding.ref)!==binding.base_commit)fail("SOURCE_REF_CONFLICT","来源引用已偏离本候选原始基线");
 const n=localIdentity(db),timestamp=Math.floor(Date.now()/1000),intent={format:"ai-fleet-source-integration/v1",integration_id:integrationId,node_id:n.node_id,node_epoch:n.sync_epoch,binding_digest:digest(binding),result_id:h.result_id,artifact_manifest_digest:h.manifest_digest,verification_id:verificationId,verification_receipt_digest:v.receipt_digest,source_task_uid:v.binding.source_task_uid,source_task_version:v.binding.source_task_version,governance_tree:v.binding.source.tree},container=join(p.descriptor.pool.root,integrationId);
 transaction(db,()=>{policy(db,policyId);assertVerificationReceiptCurrent(db,{verificationId,receiptDigest:v.receipt_digest,sourceGate});if(db.prepare("SELECT 1 FROM integration_attempts i WHERE result_id=? AND NOT EXISTS(SELECT 1 FROM integration_abandons a WHERE a.integration_id=i.integration_id)").get(h.result_id))fail("INTEGRATION_EXISTS","此候选已有保留的合并意图");if(db.prepare("SELECT count(*) n FROM integration_attempts").get().n>=1000)fail("INTEGRATION_LIMIT","保留合并运行达到上限");db.prepare("INSERT INTO integration_attempts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(integrationId,n.node_id,n.sync_epoch,policyId,verificationId,h.result_id,canonical(binding),digest(binding),canonical(intent),digest(intent),timestamp,container,at());});
 const o=importIntegrationObjects({source,identities:p.descriptor.identities,containerPath:container,packageBytes:captured.bytes,manifest:h.manifest,manifestDigest:h.manifest_digest,intent,timestamp});
 return transaction(db,()=>{current(db,row(db,integrationId),sourceGate);verifyDirectory(p.descriptor.pool);db.prepare("INSERT INTO integration_objects VALUES(?,?,?,?)").run(integrationId,canonical(o),digest(o),at());return integrationState(db,integrationId);});
}
export function abandonIntegration(db,{integrationId,reason}){if(typeof reason!=="string"||!reason.trim()||Buffer.byteLength(reason)>1024)fail("BAD_INPUT","放弃未启动合并需说明原因");return transaction(db,()=>{row(db,integrationId);if(db.prepare("SELECT 1 FROM integration_launches WHERE integration_id=?").get(integrationId))fail("INTEGRATION_ALREADY_LAUNCHED","已启动合并只能核对实际 Git 状态，不能放弃后重跑");const old=db.prepare("SELECT reason FROM integration_abandons WHERE integration_id=?").get(integrationId);if(old&&old.reason!==reason)fail("REQUEST_CONFLICT","放弃说明已固定");db.prepare("INSERT OR IGNORE INTO integration_abandons VALUES(?,?,?)").run(integrationId,reason,at());return integrationState(db,integrationId);});}
function preparedGit(db,r){const p=policy(db,r.policy_id,{active:false}),b=JSON.parse(r.binding_json),h=artifactState(db,b.transfer_id).header,o=objects(db,r.integration_id),source=sourceFor(db,p,b.base_commit);if(digest(h)!==b.header_digest)fail("INTEGRATION_CORRUPT","固定交付清单不同");const git=verifyIntegrationObjects({source,receipt:o,manifest:h.manifest,intent:JSON.parse(r.intent_json),timestamp:r.commit_timestamp});return {p,b,o,git};}
function save(db,r,receipt){const old=db.prepare("SELECT receipt_json FROM integration_receipts WHERE integration_id=?").get(r.integration_id);if(old){if(old.receipt_json!==canonical(receipt))fail("REQUEST_CONFLICT","来源合并回执已固定");}else db.prepare("INSERT INTO integration_receipts VALUES(?,?,?,?)").run(r.integration_id,canonical(receipt),digest(receipt),at());return integrationState(db,r.integration_id);}
function observe(db,r,x,sourceGate){const actual=x.git.refValue(x.b.ref);if(actual!==x.o.merge_commit)fail("INTEGRATION_EFFECT_UNCONFIRMED",actual===x.b.base_commit?"来源仍在原基线；可能未执行或尚未结束，保持启动占用":"来源引用已变化；保留现场，不覆盖或自动回滚");let error=null;try{current(db,r,sourceGate);x.git.checkoutGuard(x.b.ref);}catch(e){error=e.code??"INTEGRATION_CONTEXT_CHANGED";}return {format:"ai-fleet-integration-receipt/v1",integration_id:r.integration_id,binding_digest:r.binding_digest,intent_digest:r.intent_digest,objects_digest:digest(x.o),ref:x.b.ref,base_commit:x.b.base_commit,artifact_commit:x.b.artifact_commit,merge_commit:x.o.merge_commit,tree:x.o.tree,verification_receipt_digest:x.b.verification_receipt_digest,source_applied:true,current_at_observation:error===null,context_error:error,accepted:false,observed_at:at()};}
/** Only ref update is within a short local write transaction; imported objects precede it. */
export function executeIntegration(db,{integrationId,sourceGate}){
 outside(db);const r=row(db,integrationId),state=integrationState(db,integrationId);if(state.phase!=="ready")fail("INTEGRATION_ALREADY_LAUNCHED","合并意图不可再次启动");current(db,r,sourceGate);captureVerificationReceipt(db,{verificationId:r.verification_id,sourceGate});const x=preparedGit(db,r);x.git.checkoutGuard(x.b.ref);if(x.git.refValue(x.b.ref)!==x.b.base_commit)fail("SOURCE_REF_CONFLICT","来源已产生新提交，不能覆盖");
 transaction(db,()=>{current(db,r,sourceGate);if(integrationState(db,integrationId).phase!=="ready")fail("INTEGRATION_ALREADY_LAUNCHED","合并启动已被占用");db.prepare("INSERT INTO integration_launches VALUES(?,?,?,?)").run(integrationId,r.binding_digest,digest(x.o),at());});
 return transaction(db,()=>{current(db,r,sourceGate);x.git.compareAndSwap({ref:x.b.ref,expected:x.b.base_commit,next:x.o.merge_commit});return save(db,r,observe(db,r,x,sourceGate));});
}
/** Reconcile actual single-ref outcome. Missing/other state never causes a second update. */
export function reconcileIntegration(db,{integrationId,sourceGate}){
 outside(db);const r=row(db,integrationId),state=integrationState(db,integrationId);if(state.phase==="settled")return state;if(state.phase!=="launch_committed")fail("INTEGRATION_NOT_LAUNCHED","没有待核对的来源合并启动");const x=preparedGit(db,r);
 return transaction(db,()=>{const receipt=observe(db,r,x,sourceGate);return save(db,r,receipt);});
}
/** Historical source-applied records are not current acceptance authority. */
export function captureAppliedIntegration(db,{integrationId,sourceGate}){
 outside(db);const r=row(db,integrationId),state=integrationState(db,integrationId);if(state.phase!=="settled"||state.receipt.source_applied!==true||state.receipt.current_at_observation!==true)fail("INTEGRATION_NOT_APPLIED","缺少有效来源合并回执");current(db,r,sourceGate);captureVerificationReceipt(db,{verificationId:r.verification_id,sourceGate});const x=preparedGit(db,r),now=observe(db,r,x,sourceGate);if(!now.current_at_observation)fail("INTEGRATION_STALE","来源合并的当前授权或工作区状态改变");return {integration_id:integrationId,receipt:state.receipt,receipt_digest:state.receipt_digest,currently_valid:true,accepted:false};
}

/** Short-transaction recheck after full capture; does not repeat file reconstruction. */
export function assertAppliedIntegrationCurrent(db,{integrationId,receiptDigest,sourceGate}){
 const r=row(db,integrationId),state=integrationState(db,integrationId);if(state.phase!=="settled"||state.receipt_digest!==receiptDigest||state.receipt.source_applied!==true||state.receipt.current_at_observation!==true)fail("INTEGRATION_NOT_APPLIED","固定来源合并回执不匹配");const p=current(db,r,sourceGate),b=JSON.parse(r.binding_json),o=objects(db,integrationId),source=sourceFor(db,p,b.base_commit),git=integrationGit({source,identities:o.source_identities,container:o.container});git.checkoutGuard(b.ref);if(git.refValue(b.ref)!==o.merge_commit)fail("INTEGRATION_STALE","来源引用已偏离验收提交");return state;
}
