import {createRequire} from "node:module";
import {randomUUID} from "node:crypto";
import {PeerError,uuid,version} from "./protocol.mjs";
import {localIdentity,transaction} from "./peers.mjs";
import {canonical,digest} from "./sync-store.mjs";
import {migrateResults,resultState} from "./results.mjs";
import {bindingState,completeBinding} from "./bindings.mjs";
import {topologyState} from "./topology.mjs";
import {captureAppliedIntegration,assertAppliedIntegrationCurrent,integrationState} from "../integration/service.mjs";
import {verificationState} from "../verification/service.mjs";
import {inspectStoppedRuns} from "../execution/stop-proof.mjs";
import {normalizeCompletionPlan,completionReady,completionContract,checkCompletionReceipt} from "./completion-contract.mjs";
const require=createRequire(import.meta.url),store=require("../store.js"),cancel=require("../cancellation_guard.js");
const fail=(code,message,status=409)=>{throw new PeerError(code,message,status);},at=()=>new Date().toISOString();
function unit(db,fn){if(!db.isTransaction)return transaction(db,fn);db.exec("SAVEPOINT completion_unit");try{const r=fn();db.exec("RELEASE completion_unit");return r;}catch(e){db.exec("ROLLBACK TO completion_unit; RELEASE completion_unit");throw e;}}
function outside(db){if(db.isTransaction)fail("TRANSACTION_CONTEXT","完整产物检查须在写事务外执行");}
export function migrateCompletion(db){return unit(db,()=>{
 migrateResults(db);db.exec("CREATE TABLE IF NOT EXISTS completion_schema(singleton INTEGER PRIMARY KEY CHECK(singleton=1),version INTEGER NOT NULL); INSERT OR IGNORE INTO completion_schema VALUES(1,1)");if(db.prepare("SELECT version FROM completion_schema").get().version!==1)fail("SCHEMA_INCOMPATIBLE","完成协议存储版本不兼容");
 db.exec([
  "CREATE TABLE IF NOT EXISTS completion_plans(completion_id TEXT PRIMARY KEY,relation_id TEXT NOT NULL UNIQUE,result_id TEXT NOT NULL UNIQUE,side TEXT NOT NULL CHECK(side IN('source','target')),node_id TEXT NOT NULL,node_epoch TEXT NOT NULL,task_id INTEGER NOT NULL,task_version INTEGER NOT NULL,integration_id TEXT,plan_json TEXT NOT NULL,plan_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
  "CREATE TABLE IF NOT EXISTS completion_members(completion_id TEXT NOT NULL,task_id INTEGER NOT NULL,task_uid TEXT NOT NULL,task_version INTEGER NOT NULL,PRIMARY KEY(completion_id,task_id));",
  "CREATE INDEX IF NOT EXISTS completion_member_task ON completion_members(task_id);",
  "CREATE TABLE IF NOT EXISTS completion_ready(completion_id TEXT PRIMARY KEY,ready_json TEXT NOT NULL,ready_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
  "CREATE TABLE IF NOT EXISTS completion_registrar_attempts(request_id TEXT PRIMARY KEY,completion_id TEXT NOT NULL,args_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('pending','acknowledged','rejected')),receipt_json TEXT,error_code TEXT,created_at TEXT NOT NULL);",
  "CREATE UNIQUE INDEX IF NOT EXISTS completion_one_attempt ON completion_registrar_attempts(completion_id) WHERE state='pending';",
  "CREATE TABLE IF NOT EXISTS completion_retirements(completion_id TEXT PRIMARY KEY,receipt_json TEXT NOT NULL,receipt_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
  "CREATE TABLE IF NOT EXISTS completion_settlements(completion_id TEXT PRIMARY KEY,receipt_json TEXT NOT NULL,receipt_digest TEXT NOT NULL,created_at TEXT NOT NULL);",
  "CREATE TABLE IF NOT EXISTS completion_write_permits(task_id INTEGER PRIMARY KEY);",
  "CREATE TRIGGER IF NOT EXISTS completion_task_freeze BEFORE UPDATE ON tasks WHEN EXISTS(SELECT 1 FROM completion_plans p JOIN completion_members m USING(completion_id) WHERE m.task_id=OLD.id AND NOT EXISTS(SELECT 1 FROM completion_settlements s WHERE s.completion_id=p.completion_id)) AND NOT EXISTS(SELECT 1 FROM completion_write_permits w WHERE w.task_id=OLD.id) AND NOT EXISTS(SELECT 1 FROM result_recovery_permits w WHERE w.task_id=OLD.id) BEGIN SELECT RAISE(ABORT,'COMPLETION_COMMITTED: task awaits exact completion'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_child_hold BEFORE INSERT ON tasks WHEN EXISTS(SELECT 1 FROM completion_members m JOIN completion_plans p USING(completion_id) WHERE m.task_id=NEW.parent_id AND NOT EXISTS(SELECT 1 FROM completion_settlements s WHERE s.completion_id=p.completion_id)) BEGIN SELECT RAISE(ABORT,'COMPLETION_COMMITTED: frozen scope cannot grow'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_member_retention BEFORE DELETE ON tasks WHEN EXISTS(SELECT 1 FROM completion_members m WHERE m.task_id=OLD.id) BEGIN SELECT RAISE(ABORT,'completion task evidence must be retained'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_topology_hold BEFORE INSERT ON topology_operations WHEN EXISTS(SELECT 1 FROM json_each(NEW.desired_json,'$.vertices') v JOIN json_each(NEW.before_json,'$.vertices') b ON json_extract(b.value,'$.task_uid')=json_extract(v.value,'$.task_uid') WHERE json_extract(v.value,'$.parent_uid') IS NOT json_extract(b.value,'$.parent_uid') AND EXISTS(SELECT 1 FROM completion_members m JOIN completion_plans p USING(completion_id) WHERE NOT EXISTS(SELECT 1 FROM completion_settlements s WHERE s.completion_id=p.completion_id) AND m.task_uid IN(json_extract(v.value,'$.task_uid'),json_extract(v.value,'$.parent_uid'),json_extract(b.value,'$.parent_uid')))) BEGIN SELECT RAISE(ABORT,'COMPLETION_COMMITTED: frozen scope cannot be reparented'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_cancel_hold BEFORE INSERT ON delegation_cancellations WHEN EXISTS(SELECT 1 FROM completion_plans p WHERE p.relation_id=NEW.relation_id) BEGIN SELECT RAISE(ABORT,'COMPLETION_COMMITTED: completion cannot become cancellation'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_rejection_hold BEFORE INSERT ON result_decisions WHEN json_extract(NEW.decision_json,'$.kind')<>'result_accepted' AND EXISTS(SELECT 1 FROM completion_plans p WHERE p.result_id=NEW.result_id) BEGIN SELECT RAISE(ABORT,'COMPLETION_COMMITTED: owner decision is fixed'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_accept_guard BEFORE INSERT ON result_decisions WHEN json_extract(NEW.decision_json,'$.kind')='result_accepted' AND NOT EXISTS(SELECT 1 FROM completion_plans p JOIN completion_retirements r USING(completion_id) JOIN completion_write_permits w ON w.task_id=p.task_id WHERE p.result_id=NEW.result_id AND p.completion_id=json_extract(NEW.decision_json,'$.completion_id') AND p.plan_digest=json_extract(NEW.decision_json,'$.plan_digest') AND r.receipt_digest=json_extract(NEW.decision_json,'$.retirement_digest')) BEGIN SELECT RAISE(ABORT,'COMPLETION_REQUIRED: exact local plan and registrar proof required'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_attempt_identity BEFORE UPDATE OF request_id,completion_id,args_json,created_at ON completion_registrar_attempts BEGIN SELECT RAISE(ABORT,'completion attempt identity is immutable'); END;",
  "CREATE TRIGGER IF NOT EXISTS completion_attempt_terminal BEFORE UPDATE ON completion_registrar_attempts WHEN OLD.state<>'pending' BEGIN SELECT RAISE(ABORT,'completion attempt is terminal'); END;"
 ].join("\n"));
 for(const t of ["completion_plans","completion_members","completion_ready","completion_retirements","completion_settlements"]){db.exec("CREATE TRIGGER IF NOT EXISTS "+t+"_immutable BEFORE UPDATE ON "+t+" BEGIN SELECT RAISE(ABORT,'completion history is immutable'); END");db.exec("CREATE TRIGGER IF NOT EXISTS "+t+"_retained BEFORE DELETE ON "+t+" BEGIN SELECT RAISE(ABORT,'completion history must be retained'); END");}
 db.exec("CREATE TRIGGER IF NOT EXISTS completion_attempt_retained BEFORE DELETE ON completion_registrar_attempts BEGIN SELECT RAISE(ABORT,'completion history must be retained'); END");
});}
function row(db,id){uuid(id,"completion_id");const r=db.prepare("SELECT * FROM completion_plans WHERE completion_id=?").get(id);if(!r)fail("NOT_FOUND","完成意图不存在",404);const n=localIdentity(db);if(r.node_id!==n.node_id||r.node_epoch!==n.sync_epoch)fail("COMPLETION_RECOVERY_REQUIRED","旧节点代次的完成意图不能继续");const p=normalizeCompletionPlan(JSON.parse(r.plan_json));if(digest(p)!==r.plan_digest)fail("COMPLETION_CORRUPT","完成意图摘要改变");return r;}
function document(db,table,id,column){const r=db.prepare("SELECT * FROM "+table+" WHERE completion_id=?").get(id);if(!r)return null;const d=JSON.parse(r[column+"_json"]);if(digest(d)!==r[column+"_digest"])fail("COMPLETION_CORRUPT","完成回执摘要改变");return d;}
export function completionState(db,id){const r=row(db,id),ready=document(db,"completion_ready",id,"ready"),retirement=document(db,"completion_retirements",id,"receipt"),settlement=document(db,"completion_settlements",id,"receipt");return {completion_id:id,side:r.side,phase:settlement?"settled":retirement?"retired":ready?"ready":"prepared",plan:JSON.parse(r.plan_json),plan_digest:r.plan_digest,ready,retirement,settlement,accepted:!!settlement,attempts:db.prepare("SELECT request_id,state,error_code FROM completion_registrar_attempts WHERE completion_id=? ORDER BY rowid").all(id)};}
function task(db,p,side){const uid=p.relation[side+"_task_uid"],t=db.prepare("SELECT * FROM tasks WHERE task_uid=?").get(uid);if(!t||t.aggregate_version!==p[side+"_task_version"]||t.archived_at||t.human_gate||t.status==="in_progress"||side==="source"&&t.status==="done"||t.kind==="decision"||t.waiting_for==="decision")fail("COMPLETION_TASK_HELD","任务版本、人工闸或待决策状态不允许完成");
 if(cancel.held(db,t.id)||db.prepare("SELECT 1 FROM delegation_cancellations WHERE relation_id=?").get(p.relation.relation_id))fail("CANCELLATION_PENDING","取消流程不能被完成覆盖");
 const deps=JSON.parse(t.blocked_by);if(deps.some(id=>db.prepare("SELECT status,archived_at FROM tasks WHERE id=?").get(id)?.status!=="done"))fail("DEPENDENCY_PENDING","本地依赖尚未完成");
 if(db.prepare("SELECT 1 FROM tasks WHERE parent_id=? AND archived_at IS NULL AND status<>'done'").get(t.id))fail("CHILDREN_PENDING","本地子任务尚未完成");
 if(topologyState(db,p.relation.project_id).phase!=="ready")fail("TOPOLOGY_PENDING","本地结构尚未稳定");return t;
}
function activeResult(db,p,side){const r=resultState(db,p.result_id),b=bindingState(db,p.relation.relation_id);if(r.side!==side||r.decision||r.body_digest!==p.body_digest||r.body.process_result.status!=="success"||canonical(r.body.relation)!==canonical(p.relation)||r.body.target_task_version!==p.target_task_version||r.body.scope.scope_digest!==p.scope_digest||r.body.scope.fixture_runs!==p.fixture_runs||b.state!=="confirmed"||b.side!==side)fail("COMPLETION_RESULT_CHANGED","候选或绑定已变化");return {result:r,binding:b,task:task(db,p,side)};}
function scope(db,root,project){const all=db.prepare("SELECT t.id,t.task_uid,t.aggregate_version,t.parent_id,p.project_id FROM tasks t LEFT JOIN broker_task_projects p ON p.task_id=t.id AND p.task_uid=t.task_uid").all(),children=new Map();for(const t of all){if(!children.has(t.parent_id))children.set(t.parent_id,[]);children.get(t.parent_id).push(t);}const selected=[],seen=new Set(),queue=[all.find(t=>t.id===root)];for(let i=0;i<queue.length;i++){const t=queue[i];if(!t||seen.has(t.id))fail("BAD_COMPLETION_SCOPE","完成子树重复或缺失");seen.add(t.id);if(t.project_id!==project)fail("PROJECT_BOUNDARY","完成子树含未登记或跨项目任务");selected.push(t);queue.push(...(children.get(t.id)||[]));if(selected.length>10000)fail("SCOPE_LIMIT","完成子树超过上限");}return selected;}
function insertPlan(db,{p,side,integrationId=null}){const n=localIdentity(db),t=task(db,p,side);if(db.prepare("SELECT count(*) n FROM completion_plans").get().n>=1000)fail("COMPLETION_LIMIT","保留完成意图达到上限");db.prepare("INSERT INTO completion_plans VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(p.completion_id,p.relation.relation_id,p.result_id,side,n.node_id,n.sync_epoch,t.id,t.aggregate_version,integrationId,canonical(p),digest(p),at());for(const m of scope(db,t.id,p.relation.project_id))db.prepare("INSERT INTO completion_members VALUES(?,?,?,?)").run(p.completion_id,m.id,m.task_uid,m.aggregate_version);}
/** Explicit trusted local operator action. Never available to peer/MCP execution identities. */
export function prepareCompletion(db,{completionId,integrationId,expectedSourceVersion,note,allowFixture=false,sourceGate}){
 outside(db);uuid(completionId,"completion_id");uuid(integrationId,"integration_id");version(expectedSourceVersion);migrateCompletion(db);
 const old=db.prepare("SELECT * FROM completion_plans WHERE completion_id=?").get(completionId);if(old){const p=JSON.parse(row(db,completionId).plan_json);if(old.side!=="source"||old.integration_id!==integrationId||p.source_task_version!==expectedSourceVersion||p.decision.note!==note||p.decision.allow_fixture!==allowFixture)fail("REQUEST_CONFLICT","完成编号已固定");return completionState(db,completionId);}
 const applied=captureAppliedIntegration(db,{integrationId,sourceGate}),i=integrationState(db,integrationId),v=verificationState(db,i.binding.verification_id),r=resultState(db,i.binding.result_id);
 const p=normalizeCompletionPlan({schema_version:1,kind:"source_acceptance",completion_id:completionId,relation:r.body.relation,result_id:r.result_id,body_digest:r.body_digest,source_task_version:expectedSourceVersion,target_task_version:r.body.target_task_version,verification_receipt_digest:v.receipt_digest,integration_receipt_digest:applied.receipt_digest,artifact_manifest_digest:v.binding.artifact_manifest_digest,source_merge_commit:applied.receipt.merge_commit,source_tree:applied.receipt.tree,scope_digest:r.body.scope.scope_digest,fixture_runs:r.body.scope.fixture_runs,decision:{kind:"operator",note,allow_fixture:allowFixture}});
 if(v.binding.source_task_version!==expectedSourceVersion)fail("COMPLETION_TASK_HELD","来源版本不匹配独立验证");
 return unit(db,()=>{const prior=db.prepare("SELECT plan_json,integration_id FROM completion_plans WHERE completion_id=?").get(completionId);if(prior){if(prior.plan_json!==canonical(p)||prior.integration_id!==integrationId)fail("REQUEST_CONFLICT","完成编号已固定");return completionState(db,completionId);}assertAppliedIntegrationCurrent(db,{integrationId,receiptDigest:p.integration_receipt_digest,sourceGate});activeResult(db,p,"source");insertPlan(db,{p,side:"source",integrationId});return completionState(db,completionId);});
}
function grant(db,p,peer,remoteSide){const d=p.relation,n=localIdentity(db),own=remoteSide==="source"?"target":"source",actual=db.prepare("SELECT * FROM federation_peers WHERE peer_node_id=?").get(d[remoteSide+"_node_id"]);if(n.node_id!==d[own+"_node_id"]||n.sync_epoch!==d[own+"_epoch"]||!actual||actual.status!=="active"||actual.peer_epoch!==d[remoteSide+"_epoch"]||actual.credential_version!==peer.credential_version||peer.peer_node_id!==actual.peer_node_id||peer.peer_epoch!==actual.peer_epoch||!JSON.parse(actual.projects_json).includes(d.project_id)||!JSON.parse(actual.scopes_json).includes("delegation:complete")||!peer.scopes.includes("delegation:complete")||!peer.projects.includes(d.project_id)||db.prepare("SELECT 1 FROM federation_retired_epochs WHERE origin_node_id=? AND origin_epoch=?").get(actual.peer_node_id,actual.peer_epoch))fail("FORBIDDEN","完成协议的对端授权无效",403);}
function targetReady(db,p){const x=activeResult(db,p,"target");if(!x.binding.binding_authorized)fail("SOURCE_REVOKED","来源绑定授权失效");const members=db.prepare("SELECT task_id,task_uid,task_version FROM result_members WHERE result_id=? ORDER BY task_uid").all(p.result_id);for(const m of members){const t=db.prepare("SELECT aggregate_version FROM tasks WHERE id=? AND task_uid=?").get(m.task_id,m.task_uid);if(t?.aggregate_version!==m.task_version)fail("COMPLETION_TASK_HELD","封存子树版本变化");}
 const n=localIdentity(db),runs=members.flatMap(m=>db.prepare("SELECT * FROM task_runs WHERE task_id=? AND task_uid=?").all(m.task_id,m.task_uid)),stopped=inspectStoppedRuns(db,{nodeId:n.node_id,nodeEpoch:n.sync_epoch,members,runs});if(stopped.blockers.length||stopped.fixtureRuns!==p.fixture_runs)fail("STOP_UNCONFIRMED","停止证据变化");return completionReady(p);}
export function receiveCompletion(db,peer,plan){const p=normalizeCompletionPlan(plan);return unit(db,()=>{grant(db,p,peer,"source");const old=db.prepare("SELECT * FROM completion_plans WHERE completion_id=?").get(p.completion_id);if(old){if(row(db,p.completion_id).plan_json!==canonical(p)||old.side!=="target")fail("REQUEST_CONFLICT","来源完成意图改变");return document(db,"completion_ready",p.completion_id,"ready");}const ready=targetReady(db,p);insertPlan(db,{p,side:"target"});db.prepare("INSERT INTO completion_ready VALUES(?,?,?,?)").run(p.completion_id,canonical(ready),digest(ready),at());return ready;});}
export function recordCompletionReady(db,{completionId,ready,authorize=()=>{}}){return unit(db,()=>{authorize();const r=row(db,completionId),p=JSON.parse(r.plan_json);if(r.side!=="source")fail("FORBIDDEN","仅来源记录执行端就绪",403);completionContract(p,ready);const old=document(db,"completion_ready",completionId,"ready");if(old){if(canonical(old)!==canonical(ready))fail("REQUEST_CONFLICT","就绪回执改变");}else db.prepare("INSERT INTO completion_ready VALUES(?,?,?,?)").run(completionId,canonical(ready),digest(ready),at());return completionState(db,completionId);});}
export function startCompletionAttempt(db,{completionId,expectedVersion,authorize=()=>{}}){return unit(db,()=>{authorize();const r=row(db,completionId),s=completionState(db,completionId);if(s.phase==="settled"||s.phase==="retired")fail("COMPLETION_FINISHED","登记已结束");if(!s.ready)fail("COMPLETION_NOT_READY","先取得执行端实际就绪回执");activeResult(db,s.plan,r.side);const old=db.prepare("SELECT args_json FROM completion_registrar_attempts WHERE completion_id=? AND state='pending'").get(completionId);if(old)return JSON.parse(old.args_json);version(expectedVersion);if(db.prepare("SELECT count(*) n FROM completion_registrar_attempts WHERE completion_id=?").get(completionId).n>=1000)fail("COMPLETION_LIMIT","完成登记尝试达到上限");const args={request_id:randomUUID(),expected_version:expectedVersion,completion:completionContract(s.plan,s.ready)};db.prepare("INSERT INTO completion_registrar_attempts VALUES(?,?,?,'pending',NULL,NULL,?)").run(args.request_id,completionId,canonical(args),at());return args;});}
export function rejectCompletionAttempt(db,{completionId,requestId,code,authorize=()=>{}}){if(code!=="GRAPH_VERSION_CONFLICT")fail("UNKNOWN_REMOTE_OUTCOME","此错误不能证明登记请求未生效");return unit(db,()=>{authorize();row(db,completionId);const a=db.prepare("SELECT * FROM completion_registrar_attempts WHERE request_id=? AND completion_id=?").get(requestId,completionId);if(!a)fail("NOT_FOUND","登记请求不存在",404);if(a.state==="rejected"&&a.error_code===code)return completionState(db,completionId);if(a.state!=="pending")fail("CONFLICT","登记请求已结束");db.prepare("UPDATE completion_registrar_attempts SET state='rejected',error_code=? WHERE request_id=?").run(code,requestId);return completionState(db,completionId);});}
export function recordCompletionRetirement(db,{completionId,requestId=null,receipt,authorize=()=>{}}){return unit(db,()=>{authorize();const r=row(db,completionId),s=completionState(db,completionId),b=bindingState(db,r.relation_id),c=completionContract(s.plan,s.ready);const pending=receipt?.kind==="relation_completion_pending";
 if(pending){const expected={schema_version:1,kind:"relation_completion_pending",relation_id:r.relation_id,completion_digest:digest(c),graph_id:s.plan.relation.graph_id,graph_epoch:s.plan.relation.graph_epoch,graph_version:receipt.graph_version,approved_by:receipt.approved_by,completed:false,dispatch_ready:false};version(receipt.graph_version);if(canonical(expected)!==canonical(receipt)||!Array.isArray(receipt.approved_by)||receipt.approved_by.length>1||receipt.approved_by.some(x=>![s.plan.relation.source_node_id,s.plan.relation.target_node_id].includes(x)))fail("RECEIPT_MISMATCH","待完成登记回执不匹配");}
 else checkCompletionReceipt(receipt,c,{registrarNodeId:b.registrar_node_id,registrarEpoch:b.registrar_epoch});
 if(requestId){const a=db.prepare("SELECT * FROM completion_registrar_attempts WHERE request_id=? AND completion_id=?").get(requestId,completionId);if(!a)fail("NOT_FOUND","登记请求不存在",404);if(a.state!=="pending"){if(a.state!=="acknowledged"||a.receipt_json!==canonical(receipt))fail("REQUEST_CONFLICT","登记响应改变");}else db.prepare("UPDATE completion_registrar_attempts SET state='acknowledged',receipt_json=? WHERE request_id=?").run(canonical(receipt),requestId);}
 if(!pending){const old=document(db,"completion_retirements",completionId,"receipt");if(old){if(canonical(old)!==canonical(receipt))fail("REQUEST_CONFLICT","完成登记回执改变");}else db.prepare("INSERT INTO completion_retirements VALUES(?,?,?,?)").run(completionId,canonical(receipt),digest(receipt),at());}return completionState(db,completionId);
});}
/** Source full byte/authority check is performed immediately before consuming acceptance.
 * Task/result/binding/settlement change in one local transaction. No cross-task auto-approval. */
export function settleCompletion(db,{completionId,sourceGate,authorize=()=>{}}){
 outside(db);const r=row(db,completionId),s=completionState(db,completionId);if(s.phase==="settled")return s;if(s.phase!=="retired")fail("COMPLETION_NOT_RETIRED","尚未收到双端完成登记证明");if(r.side==="source")try{captureAppliedIntegration(db,{integrationId:r.integration_id,sourceGate});}catch(e){const latest=completionState(db,completionId);if(latest.phase==="settled")return latest;throw e;}
 return unit(db,()=>{authorize();const fresh=completionState(db,completionId);if(fresh.phase==="settled")return fresh;const p=s.plan,x=activeResult(db,p,r.side);if(r.side==="source")assertAppliedIntegrationCurrent(db,{integrationId:r.integration_id,receiptDigest:p.integration_receipt_digest,sourceGate});else targetReady(db,p);
  const decision={schema_version:1,kind:"result_accepted",result_id:p.result_id,relation_id:r.relation_id,body_digest:p.body_digest,completion_id:completionId,plan_digest:r.plan_digest,retirement_digest:digest(s.retirement),note:p.decision.note};
  db.prepare("INSERT INTO completion_write_permits VALUES(?)").run(r.task_id);db.prepare("INSERT INTO result_decisions VALUES(?,?,?,?,?)").run(r.result_id,completionId,canonical(decision),digest(decision),at());
  if(r.side==="source")completeBinding(db,{relationId:r.relation_id,receipt:s.retirement});
  if(x.task.status!=="done")store.resolve(db,{id:r.task_id,expectedVersion:r.task_version,verdict:"approve",disposition:"close",resolvedBy:"federation",note:p.decision.note,verifyOk:r.side==="source"?true:undefined,cascadeVerified:false,prepareResolution:()=>{if(r.side==="source")db.prepare("UPDATE tasks SET status='waiting',waiting_for='review',result=? WHERE id=?").run("跨端验收："+p.result_id+"\n来源合并："+p.source_merge_commit,r.task_id);return {};}});
  if(r.side==="target")completeBinding(db,{relationId:r.relation_id,receipt:s.retirement});
  db.prepare("DELETE FROM completion_write_permits WHERE task_id=?").run(r.task_id);
  const after=store.get(db,r.task_id),receipt={schema_version:1,kind:"completion_settled",completion_id:completionId,side:r.side,plan_digest:r.plan_digest,retirement_digest:digest(s.retirement),task_uid:after.task_uid,task_version:after.aggregate_version,accepted:true,fixture_runs:p.fixture_runs,settled_at:at()};
  db.prepare("INSERT INTO completion_settlements VALUES(?,?,?,?)").run(completionId,canonical(receipt),digest(receipt),at());if(after.parent_id!==null)store.rearmDone(db,{parentId:after.parent_id});return completionState(db,completionId);
 });
}
